### ISSUE TITLE
Package not working anymore

### ISSUE THREAD

**Issue by MicheleMasini1996** [peterwittek/ncpol2sdpa#44]
Copying and pasting codes from the tutorial or from the examples, I get errors. 
For instance, the first example from the tutorial:

    from ncpol2sdpa import *
    n_vars = 2 # Number of variables
    level = 2  # Requested level of relaxation
    x = generate_variables('x', n_vars)
    obj = x[0]*x[1] + x[1]*x[0]
    inequalities = [-x[1]**2 + x[1] + 0.5>=0]
    substitutions = {x[0]**2 : x[0]}
    sdp = SdpRelaxation(x)
    sdp.get_relaxation(level, objective=obj, inequalities=inequalities, substitutions=substitutions)                
    sdp.solve()
    print(sdp.primal, sdp.dual, sdp.status)

returns the following error:

Traceback (most recent call last):
  File "different-prob.py", line 16, in <module>
    sdp.solve()
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/ncpol2sdpa/sdp_relaxation.py", line 112, in solve
    solve_sdp(self, solver, solverparameters)
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/ncpol2sdpa/solver_common.py", line 127, in solve_sdp
    solve_with_cvxopt(sdp, solverparameters)
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/ncpol2sdpa/picos_utils.py", line 20, in solve_with_cvxopt
    P = convert_to_picos(sdp)
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/ncpol2sdpa/picos_utils.py", line 97, in convert_to_picos
    for k in constraint.factors:
AttributeError: 'SymmetricVariable' object has no attribute 'factors'

**Comment by peterjbrown519** [comment]
Hi,
The package no longer works with picos after they made a substantial change to their code. You can still use the package if you use the mosek or sdpa solvers. Once you have them installed you can then solve the sdp using `sdp.solve('mosek')` or `sdp.solve('sdpa')` for example. 

Alternatively, you can probably try to install an older version of picos and cvxopt, before they made the substantial changes, but it is easier to just install one of the alternative solvers I mentioned.

**Comment by MicheleMasini1996** [comment]
Thank you very much! 
It seems that with the mosek solver there are some problems as well. Anyway, it works fine with sdpa.

Do you prefer that I close the issue?

**Comment by peterjbrown519** [comment]
What issues are you having with mosek? As far as I am aware, mosek should still work.

**Comment by MicheleMasini1996** [comment]
Here what the terminal says:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    sdp.solve('mosek')
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/ncpol2sdpa/sdp_relaxation.py", line 112, in solve
    solve_sdp(self, solver, solverparameters)
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/ncpol2sdpa/solver_common.py", line 124, in solve_sdp
    solve_with_mosek(sdp, solverparameters)
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/ncpol2sdpa/mosek_utils.py", line 95, in solve_with_mosek
    task.optimize()
  File "/home/mason/miniconda3/envs/quantum/lib/python3.8/site-packages/mosek/__init__.py", line 7627, in optimize
    raise Error(rescode(res),msg)
mosek.Error: rescode.err_missing_license_file(1008): License cannot be located. The default search path is ':/home/mason/mosek/mosek.lic:'.

**Comment by peterjbrown519** [comment]
You need to get a mosek.lic license file from their website and place it in the directory /home/mason/mosek/. These license files are free if you have an academic email address. After that it should work.

**Comment by MicheleMasini1996** [comment]
You are right, thank you again!
